/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raicesDePolinomios;

/**
 *
 * @author Admin
 */
public class PoliCalcView extends javax.swing.JFrame {

    /**
     * Creates new form PoliCalcView
     */
    public PoliCalcView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelPrincipal = new javax.swing.JPanel();
        panelDivision = new javax.swing.JPanel();
        labelA = new javax.swing.JLabel();
        textA = new javax.swing.JTextField();
        comboMetodo = new javax.swing.JComboBox<>();
        labelMetodo = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        textC = new javax.swing.JTextField();
        labelCociente = new javax.swing.JLabel();
        textCociente = new javax.swing.JTextField();
        labelResto = new javax.swing.JLabel();
        textResto = new javax.swing.JTextField();
        buttonDividir = new javax.swing.JButton();
        textB = new javax.swing.JTextField();
        panelRaizAprox = new javax.swing.JPanel();
        labelEpsilon = new javax.swing.JLabel();
        textEpsilon = new javax.swing.JTextField();
        textValorInicial = new javax.swing.JTextField();
        textResultado = new javax.swing.JTextField();
        labelValorInicial = new javax.swing.JLabel();
        buttonCalcular = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        panelRaices = new javax.swing.JPanel();
        labelReales = new javax.swing.JLabel();
        textReales = new javax.swing.JTextField();
        textRacionales = new javax.swing.JTextField();
        labelRacionales = new javax.swing.JLabel();
        labelEnteras = new javax.swing.JLabel();
        buttonRaices = new javax.swing.JButton();
        textEnteras = new javax.swing.JTextField();
        panelPolinomio = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelPolinomio = new javax.swing.JLabel();
        panelTerminos = new javax.swing.JPanel();
        buttonAgregarTerminos = new javax.swing.JButton();
        buttonQuitarTerminos = new javax.swing.JButton();
        panelCotas = new javax.swing.JPanel();
        comboMetodoCotas = new javax.swing.JComboBox<>();
        labelCotaInfNeg = new javax.swing.JLabel();
        labelCotaInfPos = new javax.swing.JLabel();
        textCotaInfNeg = new javax.swing.JTextField();
        textCotaInfPos = new javax.swing.JTextField();
        labelCotaSupNeg = new javax.swing.JLabel();
        textCotaSupPos = new javax.swing.JTextField();
        textCotaSupNeg = new javax.swing.JTextField();
        labelCotaSupPos = new javax.swing.JLabel();
        buttonCotas = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelA.setText("a:");

        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "Horner Simple ( x+a )", "Horner Simple ( ax + b )", "horner Doble (x^2 + ax + b)", "horner Doble (ax^2 + bx + c)" }));

        labelMetodo.setText("Seleccionar:");

        labelB.setText("b:");

        labelC.setText("c:");

        labelCociente.setText("Cociente:");

        labelResto.setText("Resto:");

        buttonDividir.setText("Dividir");

        javax.swing.GroupLayout panelDivisionLayout = new javax.swing.GroupLayout(panelDivision);
        panelDivision.setLayout(panelDivisionLayout);
        panelDivisionLayout.setHorizontalGroup(
            panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivisionLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelDivisionLayout.createSequentialGroup()
                            .addComponent(labelMetodo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDivisionLayout.createSequentialGroup()
                            .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCociente)
                                .addComponent(labelResto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textCociente)
                                .addComponent(textResto)))
                        .addGroup(panelDivisionLayout.createSequentialGroup()
                            .addComponent(labelA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDivisionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(buttonDividir)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelDivisionLayout.setVerticalGroup(
            panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetodo)
                    .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(textA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelB)
                    .addComponent(labelC)
                    .addComponent(textC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCociente)
                    .addComponent(textCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResto)
                    .addComponent(textResto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDividir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelEpsilon.setText("Epsilon");

        labelValorInicial.setText("Valor Inicial");

        buttonCalcular.setText("Calcular");

        labelResultado.setText("Resultado:");

        javax.swing.GroupLayout panelRaizAproxLayout = new javax.swing.GroupLayout(panelRaizAprox);
        panelRaizAprox.setLayout(panelRaizAproxLayout);
        panelRaizAproxLayout.setHorizontalGroup(
            panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaizAproxLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRaizAproxLayout.createSequentialGroup()
                        .addComponent(labelResultado)
                        .addGap(18, 18, 18)
                        .addComponent(textResultado))
                    .addGroup(panelRaizAproxLayout.createSequentialGroup()
                        .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEpsilon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEpsilon))
                        .addGap(18, 18, 18)
                        .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRaizAproxLayout.createSequentialGroup()
                                .addComponent(textValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(buttonCalcular))
                            .addComponent(labelValorInicial))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRaizAproxLayout.setVerticalGroup(
            panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaizAproxLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRaizAproxLayout.createSequentialGroup()
                        .addComponent(labelValorInicial)
                        .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCalcular)))
                    .addGroup(panelRaizAproxLayout.createSequentialGroup()
                        .addComponent(labelEpsilon)
                        .addComponent(textEpsilon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelRaizAproxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResultado)
                    .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        labelReales.setText("Reales:");

        labelRacionales.setText("Racionales:");

        labelEnteras.setText("Enteras:");

        buttonRaices.setText("Det. Raíces");

        javax.swing.GroupLayout panelRaicesLayout = new javax.swing.GroupLayout(panelRaices);
        panelRaices.setLayout(panelRaicesLayout);
        panelRaicesLayout.setHorizontalGroup(
            panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRaicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRacionales)
                    .addComponent(labelReales)
                    .addComponent(labelEnteras))
                .addGap(18, 18, 18)
                .addGroup(panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textRacionales)
                    .addComponent(textReales, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEnteras, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(buttonRaices)
                .addGap(26, 26, 26))
        );
        panelRaicesLayout.setVerticalGroup(
            panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaicesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnteras)
                    .addComponent(textEnteras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRacionales)
                    .addComponent(textRacionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRaices))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRaicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReales)
                    .addComponent(textReales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setText("Calculadora de Polinomios");

        labelPolinomio.setText("Polinomio:");

        javax.swing.GroupLayout panelTerminosLayout = new javax.swing.GroupLayout(panelTerminos);
        panelTerminos.setLayout(panelTerminosLayout);
        panelTerminosLayout.setHorizontalGroup(
            panelTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTerminosLayout.setVerticalGroup(
            panelTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonAgregarTerminos.setText("Agregar");

        buttonQuitarTerminos.setText("Quitar");

        javax.swing.GroupLayout panelPolinomioLayout = new javax.swing.GroupLayout(panelPolinomio);
        panelPolinomio.setLayout(panelPolinomioLayout);
        panelPolinomioLayout.setHorizontalGroup(
            panelPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPolinomioLayout.createSequentialGroup()
                        .addComponent(panelTerminos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPolinomioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPolinomioLayout.createSequentialGroup()
                                .addComponent(labelTitulo)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPolinomioLayout.createSequentialGroup()
                                .addComponent(labelPolinomio)
                                .addGap(32, 32, 32)
                                .addComponent(buttonAgregarTerminos)
                                .addGap(18, 18, 18)
                                .addComponent(buttonQuitarTerminos)
                                .addGap(92, 92, 92))))))
        );
        panelPolinomioLayout.setVerticalGroup(
            panelPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomioLayout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPolinomio)
                    .addComponent(buttonAgregarTerminos)
                    .addComponent(buttonQuitarTerminos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(panelTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
//

        comboMetodoCotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Newton", "Laguerre", "Lagrange" }));

        labelCotaInfNeg.setText("Inf. Negativa");

        labelCotaInfPos.setText("Inf. Positiva");

        labelCotaSupNeg.setText("Sup. Negativa");

        labelCotaSupPos.setText("Sup. Positiva");

        buttonCotas.setText("´Cotas");

        javax.swing.GroupLayout panelCotasLayout = new javax.swing.GroupLayout(panelCotas);
        panelCotas.setLayout(panelCotasLayout);
        panelCotasLayout.setHorizontalGroup(
            panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCotasLayout.createSequentialGroup()
                .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCotasLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(comboMetodoCotas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCotasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCotasLayout.createSequentialGroup()
                                .addComponent(labelCotaInfPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCotaInfPos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCotasLayout.createSequentialGroup()
                                .addComponent(labelCotaInfNeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCotaInfNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCotasLayout.createSequentialGroup()
                                .addComponent(labelCotaSupNeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCotaSupNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCotasLayout.createSequentialGroup()
                                .addComponent(labelCotaSupPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCotaSupPos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCotasLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(buttonCotas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCotasLayout.setVerticalGroup(
            panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCotasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(comboMetodoCotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCotaSupNeg)
                        .addComponent(textCotaSupNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCotasLayout.createSequentialGroup()
                        .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCotaInfNeg)
                            .addComponent(textCotaInfNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCotaInfPos)
                            .addComponent(textCotaInfPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCotaSupPos)
                            .addComponent(textCotaSupPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCotas)
                .addGap(12, 12, 12))
        );
//
        /*javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRaizAprox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRaices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelPolinomio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );*/
        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPolinomio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(panelDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelCotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRaizAprox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRaices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelPrincipalLayout.setVerticalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addComponent(panelPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelRaizAprox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelRaices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
        /*panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRaizAprox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRaices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );*/

        panelDivision.getAccessibleContext().setAccessibleName("");
        panelDivision.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    //Botones
    public javax.swing.JButton getButtonAgregar() { return buttonAgregarTerminos; }
    public javax.swing.JButton getButtonQuitar() { return buttonQuitarTerminos; }
    public javax.swing.JButton getButtonDivir() { return buttonDividir; }
    public javax.swing.JButton getButtonCalcularNewton() { return buttonCalcular; }
    public javax.swing.JButton getButtonDetRaices() { return buttonRaices; }
    public javax.swing.JButton getButtonCotas() { return buttonCotas; }
    

    //Paneles
    public javax.swing.JPanel getPanelPrincipal() { return panelPrincipal; }
    public javax.swing.JPanel getPanelPolinomio() { return panelPolinomio; }
    public javax.swing.JPanel getPanelTerminos(){ return this.panelTerminos; }
    public javax.swing.JPanel getPanelDivision(){ return this.panelDivision; }
    public javax.swing.JPanel getPanelNewton(){ return this.panelRaizAprox; }
    public javax.swing.JPanel getPanelRaices(){ return this.panelRaices; }
    public javax.swing.JPanel getPanelCotas(){ return this.panelCotas; }
    
    //TextField
    public javax.swing.JTextField getTextA(){ return textA; }
    public javax.swing.JTextField getTextB(){ return textB; }
    public javax.swing.JTextField getTextC(){ return textC; }
    public javax.swing.JTextField getTextCociente(){ return textCociente; }
    public javax.swing.JTextField getTextEntereas(){ return textEnteras; }
    public javax.swing.JTextField getTextEpsilon(){ return textEpsilon; }
    public javax.swing.JTextField getTextRacionales(){ return textRacionales; }
    public javax.swing.JTextField getTextReales(){ return textReales; }
    public javax.swing.JTextField getTextResto(){ return textResto; }
    public javax.swing.JTextField getTextValorInicial(){ return textValorInicial; }
    public javax.swing.JTextField getTextResultado(){ return textResultado; }
    public javax.swing.JTextField getTextCotaInfNeg(){ return textCotaInfNeg; }
    public javax.swing.JTextField getTextCotaSupNeg(){ return textCotaSupNeg; }
    public javax.swing.JTextField getTextCotaInfPos(){ return textCotaInfPos; }
    public javax.swing.JTextField getTextCotaSupPos(){ return textCotaSupPos; }
    
    //ComboBox
    public javax.swing.JComboBox<String> getComboMetodo() { return comboMetodo; }
    public javax.swing.JComboBox<String> getComboMetodoCotas() { return comboMetodoCotas; }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonAgregarTerminos;
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JButton buttonCotas;
    private javax.swing.JButton buttonDividir;
    private javax.swing.JButton buttonQuitarTerminos;
    private javax.swing.JButton buttonRaices;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JComboBox<String> comboMetodoCotas;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField textResultado;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelB;
    private javax.swing.JLabel labelC;
    private javax.swing.JLabel labelCociente;
    private javax.swing.JLabel labelCotaInfNeg;
    private javax.swing.JLabel labelCotaInfPos;
    private javax.swing.JLabel labelCotaSupNeg;
    private javax.swing.JLabel labelCotaSupPos;
    private javax.swing.JLabel labelEnteras;
    private javax.swing.JLabel labelEpsilon;
    private javax.swing.JLabel labelMetodo;
    private javax.swing.JLabel labelPolinomio;
    private javax.swing.JLabel labelRacionales;
    private javax.swing.JLabel labelReales;
    private javax.swing.JLabel labelResto;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValorInicial;
    private javax.swing.JPanel panelCotas;
    private javax.swing.JPanel panelDivision;
    private javax.swing.JPanel panelPolinomio;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRaices;
    private javax.swing.JPanel panelRaizAprox;
    private javax.swing.JPanel panelTerminos;
    private javax.swing.JTextField textA;
    private javax.swing.JTextField textB;
    private javax.swing.JTextField textC;
    private javax.swing.JTextField textCociente;
    private javax.swing.JTextField textCotaInfNeg;
    private javax.swing.JTextField textCotaInfPos;
    private javax.swing.JTextField textCotaSupNeg;
    private javax.swing.JTextField textCotaSupPos;
    private javax.swing.JTextField textEnteras;
    private javax.swing.JTextField textEpsilon;
    private javax.swing.JTextField textRacionales;
    private javax.swing.JTextField textReales;
    private javax.swing.JTextField textResto;
    private javax.swing.JTextField textValorInicial;
    // End of variables declaration                   
}
